#
# Autogenerated by Thrift Compiler (0.9.3)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#
#  options string: py:new_style,tornado
#

from thrift.Thrift import TType, TMessageType, TException, TApplicationException

from thrift.transport import TTransport
from thrift.protocol import TBinaryProtocol, TProtocol
try:
  from thrift.protocol import fastbinary
except:
  fastbinary = None


class SamplingStrategyType(object):
  PROBABILISTIC = 0
  RATE_LIMITING = 1

  _VALUES_TO_NAMES = {
    0: "PROBABILISTIC",
    1: "RATE_LIMITING",
  }

  _NAMES_TO_VALUES = {
    "PROBABILISTIC": 0,
    "RATE_LIMITING": 1,
  }


class ProbabilisticSamplingStrategy(object):
  """
  Attributes:
   - samplingRate
  """

  thrift_spec = (
    None, # 0
    (1, TType.DOUBLE, 'samplingRate', None, None, ), # 1
  )

  def __init__(self, samplingRate=None,):
    self.samplingRate = samplingRate

  def read(self, iprot):
    if iprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None and fastbinary is not None:
      fastbinary.decode_binary(self, iprot.trans, (self.__class__, self.thrift_spec))
      return
    iprot.readStructBegin()
    while True:
      (fname, ftype, fid) = iprot.readFieldBegin()
      if ftype == TType.STOP:
        break
      if fid == 1:
        if ftype == TType.DOUBLE:
          self.samplingRate = iprot.readDouble()
        else:
          iprot.skip(ftype)
      else:
        iprot.skip(ftype)
      iprot.readFieldEnd()
    iprot.readStructEnd()

  def write(self, oprot):
    if oprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and self.thrift_spec is not None and fastbinary is not None:
      oprot.trans.write(fastbinary.encode_binary(self, (self.__class__, self.thrift_spec)))
      return
    oprot.writeStructBegin('ProbabilisticSamplingStrategy')
    if self.samplingRate is not None:
      oprot.writeFieldBegin('samplingRate', TType.DOUBLE, 1)
      oprot.writeDouble(self.samplingRate)
      oprot.writeFieldEnd()
    oprot.writeFieldStop()
    oprot.writeStructEnd()

  def validate(self):
    if self.samplingRate is None:
      raise TProtocol.TProtocolException(message='Required field samplingRate is unset!')
    return


  def __hash__(self):
    value = 17
    value = (value * 31) ^ hash(self.samplingRate)
    return value

  def __repr__(self):
    L = ['%s=%r' % (key, value)
      for key, value in self.__dict__.iteritems()]
    return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

  def __eq__(self, other):
    return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

  def __ne__(self, other):
    return not (self == other)

class RateLimitingSamplingStrategy(object):
  """
  Attributes:
   - maxTracesPerSecond
  """

  thrift_spec = (
    None, # 0
    (1, TType.I16, 'maxTracesPerSecond', None, None, ), # 1
  )

  def __init__(self, maxTracesPerSecond=None,):
    self.maxTracesPerSecond = maxTracesPerSecond

  def read(self, iprot):
    if iprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None and fastbinary is not None:
      fastbinary.decode_binary(self, iprot.trans, (self.__class__, self.thrift_spec))
      return
    iprot.readStructBegin()
    while True:
      (fname, ftype, fid) = iprot.readFieldBegin()
      if ftype == TType.STOP:
        break
      if fid == 1:
        if ftype == TType.I16:
          self.maxTracesPerSecond = iprot.readI16()
        else:
          iprot.skip(ftype)
      else:
        iprot.skip(ftype)
      iprot.readFieldEnd()
    iprot.readStructEnd()

  def write(self, oprot):
    if oprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and self.thrift_spec is not None and fastbinary is not None:
      oprot.trans.write(fastbinary.encode_binary(self, (self.__class__, self.thrift_spec)))
      return
    oprot.writeStructBegin('RateLimitingSamplingStrategy')
    if self.maxTracesPerSecond is not None:
      oprot.writeFieldBegin('maxTracesPerSecond', TType.I16, 1)
      oprot.writeI16(self.maxTracesPerSecond)
      oprot.writeFieldEnd()
    oprot.writeFieldStop()
    oprot.writeStructEnd()

  def validate(self):
    if self.maxTracesPerSecond is None:
      raise TProtocol.TProtocolException(message='Required field maxTracesPerSecond is unset!')
    return


  def __hash__(self):
    value = 17
    value = (value * 31) ^ hash(self.maxTracesPerSecond)
    return value

  def __repr__(self):
    L = ['%s=%r' % (key, value)
      for key, value in self.__dict__.iteritems()]
    return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

  def __eq__(self, other):
    return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

  def __ne__(self, other):
    return not (self == other)

class SamplingStrategyResponse(object):
  """
  Attributes:
   - strategyType
   - probabilisticSampling
   - rateLimitingSampling
  """

  thrift_spec = (
    None, # 0
    (1, TType.I32, 'strategyType', None, None, ), # 1
    (2, TType.STRUCT, 'probabilisticSampling', (ProbabilisticSamplingStrategy, ProbabilisticSamplingStrategy.thrift_spec), None, ), # 2
    (3, TType.STRUCT, 'rateLimitingSampling', (RateLimitingSamplingStrategy, RateLimitingSamplingStrategy.thrift_spec), None, ), # 3
  )

  def __init__(self, strategyType=None, probabilisticSampling=None, rateLimitingSampling=None,):
    self.strategyType = strategyType
    self.probabilisticSampling = probabilisticSampling
    self.rateLimitingSampling = rateLimitingSampling

  def read(self, iprot):
    if iprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None and fastbinary is not None:
      fastbinary.decode_binary(self, iprot.trans, (self.__class__, self.thrift_spec))
      return
    iprot.readStructBegin()
    while True:
      (fname, ftype, fid) = iprot.readFieldBegin()
      if ftype == TType.STOP:
        break
      if fid == 1:
        if ftype == TType.I32:
          self.strategyType = iprot.readI32()
        else:
          iprot.skip(ftype)
      elif fid == 2:
        if ftype == TType.STRUCT:
          self.probabilisticSampling = ProbabilisticSamplingStrategy()
          self.probabilisticSampling.read(iprot)
        else:
          iprot.skip(ftype)
      elif fid == 3:
        if ftype == TType.STRUCT:
          self.rateLimitingSampling = RateLimitingSamplingStrategy()
          self.rateLimitingSampling.read(iprot)
        else:
          iprot.skip(ftype)
      else:
        iprot.skip(ftype)
      iprot.readFieldEnd()
    iprot.readStructEnd()

  def write(self, oprot):
    if oprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and self.thrift_spec is not None and fastbinary is not None:
      oprot.trans.write(fastbinary.encode_binary(self, (self.__class__, self.thrift_spec)))
      return
    oprot.writeStructBegin('SamplingStrategyResponse')
    if self.strategyType is not None:
      oprot.writeFieldBegin('strategyType', TType.I32, 1)
      oprot.writeI32(self.strategyType)
      oprot.writeFieldEnd()
    if self.probabilisticSampling is not None:
      oprot.writeFieldBegin('probabilisticSampling', TType.STRUCT, 2)
      self.probabilisticSampling.write(oprot)
      oprot.writeFieldEnd()
    if self.rateLimitingSampling is not None:
      oprot.writeFieldBegin('rateLimitingSampling', TType.STRUCT, 3)
      self.rateLimitingSampling.write(oprot)
      oprot.writeFieldEnd()
    oprot.writeFieldStop()
    oprot.writeStructEnd()

  def validate(self):
    if self.strategyType is None:
      raise TProtocol.TProtocolException(message='Required field strategyType is unset!')
    return


  def __hash__(self):
    value = 17
    value = (value * 31) ^ hash(self.strategyType)
    value = (value * 31) ^ hash(self.probabilisticSampling)
    value = (value * 31) ^ hash(self.rateLimitingSampling)
    return value

  def __repr__(self):
    L = ['%s=%r' % (key, value)
      for key, value in self.__dict__.iteritems()]
    return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

  def __eq__(self, other):
    return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

  def __ne__(self, other):
    return not (self == other)
